<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE person [
    <!ELEMENT person (name, email, mobile, entities)>
    
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT mobile (#PCDATA)>
    <!ELEMENT entities (#PCDATA)>

    <!ATTLIST name id CDATA #FIXED "name">

    <!ENTITY nbsp "&#160;">
    <!ENTITY copy "&#169;">
    <!ENTITY copyright "2022, All Rights Reserved.">
]>
<person>
    <name id="name">Yubaraj Rai</name>
    <email>yubaraj.name@gmail.com</email>
    <mobile>+977 9852079777</mobile>
    <entities>&copy;&copyright;</entities>
</person>